import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { TanstackQueryProvider } from "@/providers/tanstack-query";
import { ToastProvider } from "@/components/ui/toast";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={` ${inter.className} antialiased`}>
        <TanstackQueryProvider>
          <ToastProvider>{children}</ToastProvider>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
